# Ipfs Module
# AUTO-DOC-INDEX
#
# ES: Índice rápido
#   1) Propósito del módulo
#   2) Componentes principales
#   3) Puntos de extensión
#
# EN: Quick index
#   1) Module purpose
#   2) Main components
#   3) Extension points
#
# Secciones / Sections:
#   - Configuración / Configuration
#   - Lógica principal / Core logic
#   - Integraciones / Integrations

"""Publicación de snapshots en IPFS.

English:
    Snapshot publication to IPFS.
"""

import json
import os
from typing import Any, Dict

DEFAULT_IPFS_ADDR = "/dns/localhost/tcp/5001/http"


def upload_snapshot_to_ipfs(json_data: Dict[str, Any]) -> str:
    """Sube un snapshot en JSON a IPFS y devuelve el CID.

    Args:
        json_data (Dict[str, Any]): Snapshot en formato dict.

    Returns:
        str: CID generado por IPFS.

    English:
        Uploads a JSON snapshot to IPFS and returns the CID.

    Args:
        json_data (Dict[str, Any]): Snapshot dictionary.

    Returns:
        str: CID generated by IPFS.
    """
    if os.getenv("IPFS_ENABLED", "false").lower() not in {"1", "true", "yes"}:
        return ""
    ipfs_addr = os.getenv("IPFS_API_URL", DEFAULT_IPFS_ADDR)
    try:
        import ipfshttpclient
    except ModuleNotFoundError:
        return ""
    client = ipfshttpclient.connect(ipfs_addr)
    try:
        return client.add_json(json_data)
    finally:
        client.close()
