"""
======================== ÍNDICE / INDEX ========================
1. Descripción general / Overview
2. Componentes principales / Main components
3. Notas de mantenimiento / Maintenance notes

======================== ESPAÑOL ========================
Archivo: `src/centinel/core/ipfs.py`.
Este módulo forma parte de Centinel Engine y está documentado para facilitar
la navegación, mantenimiento y auditoría técnica.

Componentes detectados:
  - upload_snapshot_to_ipfs

Notas:
- Mantener esta cabecera sincronizada con cambios estructurales del archivo.
- Priorizar claridad operativa y trazabilidad del comportamiento.

======================== ENGLISH ========================
File: `src/centinel/core/ipfs.py`.
This module is part of Centinel Engine and is documented to improve
navigation, maintenance, and technical auditability.

Detected components:
  - upload_snapshot_to_ipfs

Notes:
- Keep this header in sync with structural changes in the file.
- Prioritize operational clarity and behavior traceability.
"""

# Ipfs Module
# AUTO-DOC-INDEX
#
# ES: Índice rápido
#   1) Propósito del módulo
#   2) Componentes principales
#   3) Puntos de extensión
#
# EN: Quick index
#   1) Module purpose
#   2) Main components
#   3) Extension points
#
# Secciones / Sections:
#   - Configuración / Configuration
#   - Lógica principal / Core logic
#   - Integraciones / Integrations



import json
import os
from typing import Any, Dict

DEFAULT_IPFS_ADDR = "/dns/localhost/tcp/5001/http"


def upload_snapshot_to_ipfs(json_data: Dict[str, Any]) -> str:
    """Sube un snapshot en JSON a IPFS y devuelve el CID.

    Args:
        json_data (Dict[str, Any]): Snapshot en formato dict.

    Returns:
        str: CID generado por IPFS.

    English:
        Uploads a JSON snapshot to IPFS and returns the CID.

    Args:
        json_data (Dict[str, Any]): Snapshot dictionary.

    Returns:
        str: CID generated by IPFS.
    """
    if os.getenv("IPFS_ENABLED", "false").lower() not in {"1", "true", "yes"}:
        return ""
    ipfs_addr = os.getenv("IPFS_API_URL", DEFAULT_IPFS_ADDR)
    try:
        import ipfshttpclient
    except ModuleNotFoundError:
        return ""
    client = ipfshttpclient.connect(ipfs_addr)
    try:
        return client.add_json(json_data)
    finally:
        client.close()
