#!/usr/bin/env python3
"""
Observer Pack Generator — Centinel Engine

ES: Genera un paquete ZIP estandarizado para observadores electorales con:
    - Reporte PDF en español e inglés
    - Snapshot JSON de la corrida actual
    - Merkle root de la cadena de hashes
    - Cadena de hashes completa
    - Instrucciones de verificación offline
    - Manifiesto SHA-256 de todos los archivos

EN: Generates a standardized ZIP package for electoral observers containing:
    - PDF report in Spanish and English
    - JSON snapshot of the current run
    - Hash chain Merkle root
    - Complete hash chain
    - Offline verification instructions
    - SHA-256 manifest of all files

Usage:
    python scripts/generate_observer_pack.py --source-dir data/ --output observer_pack.zip
    python scripts/generate_observer_pack.py --source-dir data/ --run-id 2025-11-30T20:00Z
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import subprocess
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))


VERIFICATION_INSTRUCTIONS_ES = """\
# Instrucciones de Verificación Offline — Centinel Engine
## Paquete de Observador Electoral

Este paquete fue generado automáticamente por Centinel Engine durante el proceso electoral.

## ¿Qué contiene este paquete?

- `report_es.pdf` — Informe de auditoría en español
- `report_en.pdf` — Audit report in English
- `snapshot.json` — Datos crudos del snapshot electoral
- `hash_chain.json` — Cadena de hashes SHA-256 de todas las capturas
- `merkle_root.txt` — Raíz Merkle de la cadena de hashes
- `VERIFICATION.md` — Este archivo
- `manifest.sha256` — SHA-256 de todos los archivos del paquete

## Cómo verificar la integridad de este paquete

### Paso 1: Verificar el manifiesto

```bash
sha256sum --check manifest.sha256
```

Todos los archivos deben reportar "OK". Si alguno falla, el paquete ha sido modificado.

### Paso 2: Verificar la cadena de hashes

Abrir `hash_chain.json` y verificar que:
1. El campo `merkle_root` coincide con el contenido de `merkle_root.txt`
2. Cada bloque `previous_hash` coincide con el `hash` del bloque anterior
3. Los timestamps son monotónicamente crecientes

### Paso 3: Verificar el ancla Bitcoin (OpenTimestamps)

Si el archivo `checkpoint.ots` está incluido:
```bash
# Instalar: pip install opentimestamps-client
ots verify checkpoint.ots
```

Esto confirma que el primer hash del día existía antes de que terminara el proceso electoral.

### Paso 4: Verificar los datos crudos

El archivo `snapshot.json` contiene los datos originales tal como fueron capturados
de los servidores del CNE. Cualquier ciudadano puede comparar estos datos con lo que
el CNE publicó oficialmente.

## ¿Qué significa si la verificación falla?

Si `sha256sum --check manifest.sha256` reporta fallos:
- El paquete fue modificado después de ser generado
- Esto no significa necesariamente fraude — puede ser un error de transmisión
- Comparar con el paquete original publicado en el panel: https://github.com/userf8a2c4/centinel-engine

Si la cadena de hashes tiene discontinuidades:
- Algunos snapshots no fueron capturados (puede ocurrir por problemas de red)
- O los datos del CNE cambiaron entre capturas — esto sí es relevante investigar

## Contacto

Para reportar irregularidades técnicas en este paquete, abrir un issue en:
https://github.com/userf8a2c4/centinel-engine/issues
"""

VERIFICATION_INSTRUCTIONS_EN = """\
# Offline Verification Instructions — Centinel Engine
## Electoral Observer Package

This package was automatically generated by Centinel Engine during the electoral process.

## Package Contents

- `report_es.pdf` — Audit report in Spanish
- `report_en.pdf` — Audit report in English
- `snapshot.json` — Raw electoral snapshot data
- `hash_chain.json` — SHA-256 hash chain of all captures
- `merkle_root.txt` — Merkle root of the hash chain
- `VERIFICATION_EN.md` — This file
- `manifest.sha256` — SHA-256 of all files in the package

## How to verify the integrity of this package

### Step 1: Verify the manifest

```bash
sha256sum --check manifest.sha256
```

All files should report "OK". If any fail, the package has been modified.

### Step 2: Verify the hash chain

Open `hash_chain.json` and verify that:
1. The `merkle_root` field matches the content of `merkle_root.txt`
2. Each block's `previous_hash` matches the `hash` of the previous block
3. Timestamps are monotonically increasing

### Step 3: Verify the Bitcoin anchor (OpenTimestamps)

If `checkpoint.ots` is included:
```bash
# Install: pip install opentimestamps-client
ots verify checkpoint.ots
```

This confirms the first hash of the day existed before the electoral process ended.

### Step 4: Verify the raw data

The `snapshot.json` file contains the original data as captured from CNE servers.
Any citizen can compare this data with what the CNE officially published.

## What does a verification failure mean?

If `sha256sum --check manifest.sha256` reports failures:
- The package was modified after generation
- This does not necessarily mean fraud — it may be a transmission error
- Compare with the original package published at the panel

If the hash chain has discontinuities:
- Some snapshots were not captured (can occur due to network issues)
- Or CNE data changed between captures — this is worth investigating

## Contact

To report technical irregularities in this package, open an issue at:
https://github.com/userf8a2c4/centinel-engine/issues
"""


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def load_snapshot(source_dir: Path) -> dict:
    """Load the most recent snapshot JSON from source_dir."""
    snapshot_files = sorted(source_dir.glob("*.json"))
    if not snapshot_files:
        return {"note": "No snapshot files found", "source_dir": str(source_dir)}
    latest = snapshot_files[-1]
    try:
        return json.loads(latest.read_text())
    except Exception as e:
        return {"error": str(e), "file": str(latest)}


def load_hash_chain(source_dir: Path) -> list[dict]:
    """Load hash chain records from source_dir."""
    chain_file = source_dir / "hash_chain.json"
    if chain_file.exists():
        try:
            data = json.loads(chain_file.read_text())
            return data if isinstance(data, list) else [data]
        except Exception:
            pass

    # Fallback: collect hash entries from individual snapshots
    entries = []
    for f in sorted(source_dir.glob("*.json")):
        try:
            snap = json.loads(f.read_text())
            if "hash" in snap or "snapshot_hash" in snap:
                entries.append({
                    "file": f.name,
                    "hash": snap.get("hash") or snap.get("snapshot_hash"),
                    "timestamp": snap.get("timestamp") or snap.get("captured_at"),
                    "previous_hash": snap.get("previous_hash"),
                })
        except Exception:
            continue
    return entries


def compute_merkle_root(hashes: list[str]) -> str:
    """Bitcoin-style Merkle root."""
    import hashlib as _h
    if not hashes:
        return ""
    if len(hashes) == 1:
        return hashes[0]
    level = hashes[:]
    while len(level) > 1:
        next_level = []
        for i in range(0, len(level), 2):
            pair = level[i] + (level[i + 1] if i + 1 < len(level) else level[i])
            next_level.append(_h.sha256(pair.encode()).hexdigest())
        level = next_level
    return level[0]


def generate_pdf_report(source_dir: Path, lang: str) -> bytes:
    """Call generate_report.py and return PDF bytes."""
    output_name = f"/tmp/centinel_report_{lang}.pdf"
    cmd = [
        sys.executable,
        str(Path(__file__).parent / "generate_report.py"),
        "--source-dir", str(source_dir),
        "--output", output_name,
        "--lang", lang,
        "--sign",
    ]
    try:
        subprocess.run(cmd, check=True, capture_output=True)
        pdf_path = Path(output_name)
        if pdf_path.exists():
            return pdf_path.read_bytes()
    except Exception as e:
        print(f"[WARNING] Could not generate PDF ({lang}): {e}", file=sys.stderr)
    return b""


def build_observer_pack(
    source_dir: Path,
    output_path: Path,
    run_id: str,
) -> str:
    """Build the observer pack ZIP and return its SHA-256."""
    snapshot = load_snapshot(source_dir)
    hash_chain = load_hash_chain(source_dir)
    hashes = [e.get("hash", "") for e in hash_chain if e.get("hash")]
    merkle_root = compute_merkle_root(hashes)

    hash_chain_json = json.dumps({
        "run_id": run_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "merkle_root": merkle_root,
        "chain_length": len(hash_chain),
        "entries": hash_chain,
    }, indent=2).encode()

    snapshot_json = json.dumps(snapshot, indent=2, ensure_ascii=False).encode()
    merkle_txt = f"{merkle_root}\n".encode()

    print(f"Generating PDF reports...")
    pdf_es = generate_pdf_report(source_dir, "es")
    pdf_en = generate_pdf_report(source_dir, "en")

    # Build in-memory manifest
    files: dict[str, bytes] = {
        "snapshot.json": snapshot_json,
        "hash_chain.json": hash_chain_json,
        "merkle_root.txt": merkle_txt,
        "VERIFICATION.md": VERIFICATION_INSTRUCTIONS_ES.encode(),
        "VERIFICATION_EN.md": VERIFICATION_INSTRUCTIONS_EN.encode(),
    }
    if pdf_es:
        files["report_es.pdf"] = pdf_es
    if pdf_en:
        files["report_en.pdf"] = pdf_en

    # Check for OTS file
    ots_candidates = list(source_dir.glob("*.ots"))
    if ots_candidates:
        files["checkpoint.ots"] = ots_candidates[0].read_bytes()

    # Build manifest
    manifest_lines = [
        f"{_sha256_bytes(content)}  {name}\n"
        for name, content in sorted(files.items())
    ]
    manifest_bytes = "".join(manifest_lines).encode()
    files["manifest.sha256"] = manifest_bytes

    # Write ZIP
    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, content in files.items():
            zf.writestr(name, content)

    pack_hash = _sha256_bytes(output_path.read_bytes())
    hash_file = output_path.with_suffix(".sha256")
    hash_file.write_text(f"{pack_hash}  {output_path.name}\n")

    return pack_hash


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate standardized observer pack ZIP for Centinel Engine"
    )
    parser.add_argument(
        "--source-dir", default="data",
        help="Directory containing snapshot JSON files (default: data/)"
    )
    parser.add_argument(
        "--output", default="observer_pack.zip",
        help="Output ZIP file path (default: observer_pack.zip)"
    )
    parser.add_argument(
        "--run-id", default=None,
        help="Run identifier (default: current UTC timestamp)"
    )
    args = parser.parse_args()

    source_dir = Path(args.source_dir)
    if not source_dir.exists():
        print(f"[ERROR] Source directory not found: {source_dir}", file=sys.stderr)
        sys.exit(1)

    run_id = args.run_id or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    output_path = Path(args.output)

    print(f"Building observer pack for run: {run_id}")
    print(f"Source: {source_dir} → Output: {output_path}")

    pack_hash = build_observer_pack(source_dir, output_path, run_id)

    print(f"\nObserver pack generated:")
    print(f"  File:    {output_path}")
    print(f"  Size:    {output_path.stat().st_size:,} bytes")
    print(f"  SHA-256: {pack_hash}")
    print(f"  Manifest: {output_path.with_suffix('.sha256')}")
    print(f"\nDistribute {output_path.name} and its SHA-256 to observers.")
    print(f"They can verify integrity with: sha256sum --check {output_path.with_suffix('.sha256').name}")


if __name__ == "__main__":
    main()
