"""
======================== ÍNDICE / INDEX ========================
1. Descripción general / Overview
2. Componentes principales / Main components
3. Notas de mantenimiento / Maintenance notes

======================== ESPAÑOL ========================
Archivo: `centinel_engine/arbitrum_hook.py`.
Este módulo forma parte de Centinel Engine y está documentado para facilitar
la navegación, mantenimiento y auditoría técnica.

Componentes detectados:
  - anchor_hash_to_arbitrum

Notas:
- Mantener esta cabecera sincronizada con cambios estructurales del archivo.
- Priorizar claridad operativa y trazabilidad del comportamiento.

======================== ENGLISH ========================
File: `centinel_engine/arbitrum_hook.py`.
This module is part of Centinel Engine and is documented to improve
navigation, maintenance, and technical auditability.

Detected components:
  - anchor_hash_to_arbitrum

Notes:
- Keep this header in sync with structural changes in the file.
- Prioritize operational clarity and behavior traceability.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


def anchor_hash_to_arbitrum(current_hash: str, config: dict[str, Any]) -> str:
    """Return the current hash unchanged when Arbitrum anchoring is disabled.

    English:
        This stub intentionally performs no blockchain call. It exists as a
        compatibility-safe extension point for future Arbitrum anchoring.

    Español:
        Este stub intencionalmente no realiza llamadas blockchain. Existe como
        un punto de extension seguro y compatible para anclaje futuro en Arbitrum.

    Args:
        current_hash: Canonical hash generated by the current pipeline step.
        config: Runtime configuration dictionary. Uses ``ENABLE_ARBITRUM``
            (default: ``False``) to decide whether the extension is active.

    Returns:
        The original ``current_hash`` unchanged.
    """
    # Extension flag with secure default / Flag de extension con default seguro.
    enabled: bool = bool(config.get("ENABLE_ARBITRUM", False))
    if not enabled:
        logger.info("Arbitrum anchoring disabled")
        return current_hash

    # Future implementation placeholder / Placeholder para implementacion futura.
    logger.info("Arbitrum anchoring stub active but not implemented yet")
    return current_hash
