"""Arbitrum anchoring extension hook (disabled by default).

This module defines a no-op extension point so future Arbitrum anchoring logic
can be enabled without changing core hash-generation code paths.

Este modulo define un punto de extension no operativo para que la logica futura
 de anclaje en Arbitrum pueda habilitarse sin cambiar los flujos centrales de
 generacion de hashes.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


def anchor_hash_to_arbitrum(current_hash: str, config: dict[str, Any]) -> str:
    """Return the current hash unchanged when Arbitrum anchoring is disabled.

    English:
        This stub intentionally performs no blockchain call. It exists as a
        compatibility-safe extension point for future Arbitrum anchoring.

    Español:
        Este stub intencionalmente no realiza llamadas blockchain. Existe como
        un punto de extension seguro y compatible para anclaje futuro en Arbitrum.

    Args:
        current_hash: Canonical hash generated by the current pipeline step.
        config: Runtime configuration dictionary. Uses ``ENABLE_ARBITRUM``
            (default: ``False``) to decide whether the extension is active.

    Returns:
        The original ``current_hash`` unchanged.
    """
    # Extension flag with secure default / Flag de extension con default seguro.
    enabled: bool = bool(config.get("ENABLE_ARBITRUM", False))
    if not enabled:
        logger.info("Arbitrum anchoring disabled")
        return current_hash

    # Future implementation placeholder / Placeholder para implementacion futura.
    logger.info("Arbitrum anchoring stub active but not implemented yet")
    return current_hash
