"""
======================== ÍNDICE / INDEX ========================
1. Descripción general / Overview
2. Componentes principales / Main components
3. Notas de mantenimiento / Maintenance notes

======================== ESPAÑOL ========================
Archivo: `centinel_engine/telegram_hook.py`.
Este módulo forma parte de Centinel Engine y está documentado para facilitar
la navegación, mantenimiento y auditoría técnica.

Componentes detectados:
  - send_alert_via_telegram

Notas:
- Mantener esta cabecera sincronizada con cambios estructurales del archivo.
- Priorizar claridad operativa y trazabilidad del comportamiento.

======================== ENGLISH ========================
File: `centinel_engine/telegram_hook.py`.
This module is part of Centinel Engine and is documented to improve
navigation, maintenance, and technical auditability.

Detected components:
  - send_alert_via_telegram

Notes:
- Keep this header in sync with structural changes in the file.
- Prioritize operational clarity and behavior traceability.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


def send_alert_via_telegram(message: str, config: dict[str, Any]) -> bool:
    """Send a critical alert via Telegram when enabled (stub currently disabled).

    English:
        This function is a compatibility-first placeholder. No external network
        call is performed in the current implementation.

    Español:
        Esta funcion es un placeholder orientado a compatibilidad. En la
        implementacion actual no se realiza ninguna llamada de red externa.

    Args:
        message: Alert text generated by the calling workflow.
        config: Runtime configuration dictionary. Uses ``ENABLE_TELEGRAM``
            (default: ``False``) to decide if this extension should run.

    Returns:
        ``False`` in the current stub implementation.
    """
    # Guard extension path behind explicit feature flag /
    # Proteger ruta de extension con feature flag explicito.
    enabled: bool = bool(config.get("ENABLE_TELEGRAM", False))
    if not enabled:
        logger.info("Telegram alert disabled")
        return False

    # Future implementation placeholder / Placeholder para implementacion futura.
    logger.info("Telegram alert stub active but not implemented yet: %s", message)
    return False
