"""Telegram alert extension hook (disabled by default).

This module exposes a stable function signature for future Telegram-based
critical alert delivery while remaining non-functional today.

Este modulo expone una firma estable para envio futuro de alertas criticas por
Telegram, manteniendose no funcional por ahora.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


def send_alert_via_telegram(message: str, config: dict[str, Any]) -> bool:
    """Send a critical alert via Telegram when enabled (stub currently disabled).

    English:
        This function is a compatibility-first placeholder. No external network
        call is performed in the current implementation.

    Español:
        Esta funcion es un placeholder orientado a compatibilidad. En la
        implementacion actual no se realiza ninguna llamada de red externa.

    Args:
        message: Alert text generated by the calling workflow.
        config: Runtime configuration dictionary. Uses ``ENABLE_TELEGRAM``
            (default: ``False``) to decide if this extension should run.

    Returns:
        ``False`` in the current stub implementation.
    """
    # Guard extension path behind explicit feature flag /
    # Proteger ruta de extension con feature flag explicito.
    enabled: bool = bool(config.get("ENABLE_TELEGRAM", False))
    if not enabled:
        logger.info("Telegram alert disabled")
        return False

    # Future implementation placeholder / Placeholder para implementacion futura.
    logger.info("Telegram alert stub active but not implemented yet: %s", message)
    return False
